### ISSUE TITLE
准确率如何计算

### ISSUE THREAD

**Issue by jackyangs** [ArthasMil/AACVP-MVSNet#1]
你好，我想问一下准确率用哪个matlab文件进行计算呢？我把下载下来了但是找不到用哪一个，希望你可以给我指点一下

**Comment by ArthasMil** [comment]
你好，感谢对本项目的关注。
关于DTU的精度验证问题，主要用到两个文件：
1. 在BaseEvalMain_web.m中，设置路径，包括验证数据路径、计算结果、ply的路径。需要注意的是，请提前创建好计算结果的文件夹，否则可能运行完第一个Ply会报错
2.等待很长时间………………直到运行完成
3. 同样在ComputeStat_web.m文件中设置对应目录，运行即可获得comp和acc
4. 对comp和acc取均值，即overall accuracy。

以上可以参考[CasMVSNet](https://github.com/alibaba/cascade-stereo/tree/master/CasMVSNet/evaluations/dtu)中的相关脚本。

希望可以帮到你。

**Comment by jackyangs** [comment]
非常感谢您的回复，我会按照上述步骤尝试一下的

**Comment by jackyangs** [comment]
非常感谢您上次的回复，我想再问一下PointCompareMain.m这个文件中需要一个ObsMask***.mat文件这个文件是如何得到的呢？

**Comment by ArthasMil** [comment]
> 非常感谢您上次的回复，我想再问一下PointCompareMain.m这个文件中需要一个ObsMask***.mat文件这个文件是如何得到的呢？
您好，ObsMask***.mat应该是在[这里](http://roboimagedata2.compute.dtu.dk/data/MVS/SampleSet.zip)下载
此外，可能还需要[这个文件]([Points](http://roboimagedata2.compute.dtu.dk/data/MVS/Points.zip)，然后将数据组织为：

```
├── DTU (can be anywhere)
│   ├── Points
│   └── ObsMask
```

[这里](https://github.com/kwea123/CasMVSNet_pl/blob/master/evaluations/dtu/README.md)有更详细的说明。

**Comment by jackyangs** [comment]
谢谢您的回复
