### ISSUE TITLE
自采数据集的参数设置

### ISSUE THREAD

**Issue by RyanLiu112** [ArthasMil/AACVP-MVSNet#11]
您好，我们使用[colmap2mvsnet.py](https://github.com/YoYo000/MVSNet/blob/master/mvsnet/colmap2mvsnet.py)得到了自采数据的相机参数，但最终输出的深度图效果较差，请问colmap2mvsnet.py中的max_d以及interval_scale参数应该如何设置？谢谢

**Comment by ArthasMil** [comment]
您好，您可以试试[这里](https://www.cnblogs.com/YongQiVisionIMAX/p/13594246.html)是否有帮助。自定义数据集一般要进行多种尝试。max_d可以设定192，interrval设置一般根据实际情况进行。

当然，也可以试试BlendedMVS的数据方法，不同场景的设置有区别。[https://github.com/YoYo000/BlendedMVS](BlendedMVS)

**Comment by RyanLiu112** [comment]
感谢您的回复！请问如果要在BlendedMVS数据集上进行测试的话，相较于DTU的代码，需要修改哪些参数呢？例如[pixel_interval](https://github.com/ArthasMil/AACVP-MVSNet/blob/439c59db962bd244ccbce21c22742d2be85f4a75/models/Module.py#L198)是否需要改小一点呢？或者您方便开源一下BlendedMVS的测试代码吗？

**Comment by ArthasMil** [comment]
你好，我是参考[这个代码](https://github.com/kwea123/CasMVSNet_pl/blob/master/datasets/blendedmvs.py)，根据框架修改的。不同的是，我没有进行文件中第100行的操作。

**Comment by RyanLiu112** [comment]
好的谢谢！问题已经解决了
