### ISSUE TITLE
Pretrained weights unavailable

### ISSUE THREAD

**Issue by anuveshkumar** [ArthasMil/AACVP-MVSNet#12]
Hi, I tried the Baidu link to get the pretrained weights but it's problematic.
I looked at the other issues, but the links for onedrive isn't working.

Can you upload the weights here, or maybe send it to my mail (anuvesh.kumar@gmail.com) ?

Thank you

**Comment by ArthasMil** [comment]
Sorry for late replay. I've shared the link via email. You may check your inbox later.

**Comment by crescent-even** [comment]
I also tried the Baidu link to get the pretrained weights but it's problematic.


Can you  send it to my mail (221612070@sust.edu.cn) ?

Thank you

**Comment by ArthasMil** [comment]
> I also tried the Baidu link to get the pretrained weights but it's problematic.
> 
> Can you send it to my mail ([221612070@sust.edu.cn](mailto:221612070@sust.edu.cn)) ?
> 
> Thank you

My sincere apology for late reply. I've sent the pretrained model on DTU. Please check your email inbox. 
Best regards.
