### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by lemonsstyle** [ArthasMil/AACVP-MVSNet#17]
Hello, I'm very interested in your experiment and want to try the effect, but I don't have enough memory to run your train and can't train it（rtx 3090 x2, bn=9）. Can you provide another link to the model file? I've tried the links you sent but they all don't work.

**Comment by ArthasMil** [comment]
I've upload the pretrained model [here](https://pan.baidu.com/s/1A405OKQKxPjR97SP8pX-Vw?pwd=ozxg). I hope it would help your research. 

Best regards.
