### ISSUE TITLE
论文中点云对比图中的点云哪里能够得到？

### ISSUE THREAD

**Issue by zhaozj19** [ArthasMil/AACVP-MVSNet#2]

**Comment by zhaozj19** [comment]
您好，我想知道您的论文里面的MVSNet的点云和CasMVSNet的点云是从哪来的？MVSNet好像只提供了R-MVSNet的点云数据。

**Comment by ArthasMil** [comment]
您好，感谢您的关注。

为了方便对比，我使用两位作者的开源代码，结合作者提供pre-trained weights，在相同的参数条件下得到的结果。
MVSNet的论文中有，作者使用了Altizure的内部库，所以没有办法直接使用。为了得到该结构下的点云，有两种简单的方式，一种是将得到的depth maps，使用作者提供的基于fusibile的后处理工具包进行深度图融合与点云重建；另一种使用Xiaoyang Guo的Pytorch实现版本（https://github.com/xy-guo/MVSNet_pytorch），用这个版本的生成深度图，并结合作者的后处理方法进行点云生成，当然也可以使用fusibile工具包进行深度图的融合、滤波、一致性检验和点云融合。
当然，这两种方式得到的点云会与原文中的略有区别，但是精度相差不大。

希望可以帮到您。

**Comment by zhaozj19** [comment]
非常谢谢您的解答！
