### ISSUE TITLE
关于模块的作用

### ISSUE THREAD

**Issue by agenthong** [ArthasMil/AACVP-MVSNet#4]
你好，看了你的文章是很棒的工作。
请问你在模型中的特征提取自注意力模块和构建成本体积的相似性度量，这两个地方哪一部分对模型提升的效果比较大？

**Comment by ArthasMil** [comment]
您好，感谢您对本工作的关注。
在消融实验部分（详见最终版论文，非Arxiv版），两个模块都有所提升。在DTU数据集下，我们还进行了不同的参数实验，许多情况下，“仅仅引入GWC测度”的效果，是优于“仅仅引入self-attention layer”的。当然，我们的分析结果和许多参数设置相关，包括了depth map估计的相关参数，也包括了post-processing的相关参数。
