### ISSUE TITLE
Pretrained model outside china

### ISSUE THREAD

**Issue by jorenvs** [ArthasMil/AACVP-MVSNet#5]
Can you upload the pre-trained model to some place that we can access from outside China? Baidu doesn't allow creating accounts without a Chinese phone number. Thanks!

**Comment by ArthasMil** [comment]
[Here](https://1drv.ms/u/s!As8QwQacjW0gyzO6ai22B-8ST6CC?e=E2VXrO) is the ckpt of our network shared at Microsoft Onedrive. I hope it would help you!

**Comment by jorenvs** [comment]
Thanks! I'm using CVP-MVSNet for now, but I have downloaded the model and will compare it later. I'll close the issue already for now.
