### ISSUE TITLE
can't download the checkpoint

### ISSUE THREAD

**Issue by Kaktusava** [ArthasMil/AACVP-MVSNet#6]
Hi, could you upload the checkpoint file to another cloud service? It's impossible to register on Baidu from outside of Cina.

**Comment by ArthasMil** [comment]
[Here](https://onedrive.live.com/?authkey=%21ALpqLbYH7xJPoII&cid=206D8D9C06C110CF&id=206D8D9C06C110CF%219651&parId=206D8D9C06C110CF%21110&o=OneUp) is the ckpt of our network shared at Microsoft Onedrive. I hope it would help you!

**Comment by Kaktusava** [comment]
Sorry, but at this link, the item might not exist or is no longer available. Could you upload again, please?

**Comment by ArthasMil** [comment]
Sorry for the unavailable link. I've shared the ckpt file again and [HERE](https://1drv.ms/u/s!As8QwQacjW0gyzO8UKEo3pLJd0EJ) is the uploaded file. 
If this link could not work. You may leave the email address and I'll send it via email.
