### ISSUE TITLE
Access to Checkpoint

### ISSUE THREAD

**Issue by eddienewton** [ArthasMil/AACVP-MVSNet#7]
Hi,

Your results look great, and I'm interested in testing your code.  Is it possible to download the pre-trained model?  I'm having a hard time downloading the one from BaiduYun.

Much appreciated!

**Comment by ArthasMil** [comment]
[HERE](https://1drv.ms/u/s!As8QwQacjW0gyzO8UKEo3pLJd0EJ) is the uploaded file. 
If this link could not work. You may leave the email address and I'll send it via email.

I hope it could help you! :D

**Comment by eddienewton** [comment]
Hi, 

Thanks for the quick response!  Unfortunately the link says "This item might not exist or is no longer available" so it might be a permissions issue.  

My email is eddienewtonian@gmail.com.  

Thank you again!

**Comment by ArthasMil** [comment]
I've sent an email with the checkpoint attached. I hope it helps.
