### ISSUE TITLE
fusibile_to_dtu_eval

### ISSUE THREAD

**Issue by mty62** [ArthasMil/AACVP-MVSNet#8]
File "fusibile_to_dtu_eval.py", line 25, in <module>
    consis_folder = consis_folders[-2]
IndexError: list index out of range

**Comment by mty62** [comment]
File "fusibile_to_dtu_eval.py", line 25, in <module>
    consis_folder = consis_folders[-1]
IndexError: list index out of range

**Comment by ArthasMil** [comment]
This variable is genereated by 'consis_folders = [f for f in listdir(scan_folder) if f.startswith('consistencyCheck-')]'

**Comment by ArthasMil** [comment]
This variable is genereated by 'consis_folders = [f for f in listdir(scan_folder) if f.startswith('consistencyCheck-')]'

You may check whether the _**scan_folder**_ containing the *.ply files those start with 'consistencyCheck-'. (print(listdir(scan_folder)) may help)

At meantime, this script is the same with Yang's script [here](https://github.com/JiayuYANG/CVP-MVSNet/blob/master/CVP_MVSNet/fusion/fusibile_to_dtu_eval.py).

**Comment by mty62** [comment]
no ply file in fusibile_fused , why?

**Comment by ArthasMil** [comment]
It happens when the CUDA/fusibile configuration is not correct. You may check [this issue](https://github.com/JiayuYANG/CVP-MVSNet/issues/8#issue-664202778) for more details.
