### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by eddienewton** [ArthasMil/AACVP-MVSNet#9]
Hi,

Thanks again for the checkpoint.  Everything works on the latest version of Pytorch.

I had a question about runtime.  Compared to UCSNet and Casmvsnet, the inference time is somewhat larger (~1.3 seconds version ~2.4 seconds).  Is it because the feature pyramid takes time to build?  For my tests on scan1, the feature pyramid took about 1.3 seconds to build.

Just want to see if my observations are inline with your experience, or if my PyTorch configuration needs to change.  

Many thanks to your help,
Eddie

**Comment by ArthasMil** [comment]
I agree with your concolusion. When inference in AACVP for DTU dataset, a pyramid with 5 layers is formed (3 layers for UCS. and CasMVS.) first and the inference process will be taken hierarchically.
